#!/usr/bin/env bash
set -x
set -e

rm -rf submit submit.zip
mkdir -p submit

# submit team.txt
printf "André Kang-Moeller,amoell\nPaul Curry,paulmc\nAbdelelah Salama,engobada" > submit/team.txt

# train model
python src/model.py train --work_dir work

# make predictions on example data submit it in pred.txt
# change the following line to use "data/input.txt" and "data/pred.txt" instead of "example" to use synthetic data
# generated by `python generate_synthetic_data.py`; useful for performance testing.
python src/model.py test --work_dir work --test_data example/input.txt --test_output example/pred.txt

# submit docker file
cp Dockerfile submit/Dockerfile

# submit source code
cp -r src submit/src

# submit checkpoints
cp -r work submit/work

cp requirements.txt submit/
cp requirements_dev.txt submit/

# make zip file
zip -r Project517Group17.zip submit
